import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { InventoryProvider } from "./inventoryContext";

export const metadata: Metadata = {
  title: "Sistema de Gestion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

          <InventoryProvider>
            {children}
          </InventoryProvider>

        <Toaster/>
      </body>
    </html>
  );
}

